# Matrices

#### Matrices are absolutely fundamental to the workings of AI and Machine Learning, providing a structured and efficient way to handle and manipulate large volumes of data

#### This code covers creating matrices, performing element-wise and matrix multiplication, and transposing matrices.

In [1]:
import numpy as np  # Import NumPy for matrix operations

# Create two 2x2 matrices
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Element-wise addition: Adds corresponding elements of A and B
mat_add = A + B  
# Result: [[1+5, 2+6], 
#          [3+7, 4+8]]

# Element-wise subtraction: Subtracts corresponding elements of B from A
mat_sub = A - B  
# Result: [[1-5, 2-6], 
#          [3-7, 4-8]]

# Matrix multiplication (dot product): Computes A * B using matrix multiplication rules
mat_mult = np.dot(A, B)  
# Result: [[(1*5 + 2*7), (1*6 + 2*8)], 
#          [(3*5 + 4*7), (3*6 + 4*8)]]

# Transpose of matrix A: Flips rows and columns
A_transpose = np.transpose(A)  
# Result: [[1, 3], 
#          [2, 4]]

# Print results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A + B (Element-wise Addition):\n", mat_add)
print("A - B (Element-wise Subtraction):\n", mat_sub)
print("A dot B (Matrix Multiplication):\n", mat_mult)
print("Transpose of A:\n", A_transpose)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B (Element-wise Addition):
 [[ 6  8]
 [10 12]]
A - B (Element-wise Subtraction):
 [[-4 -4]
 [-4 -4]]
A dot B (Matrix Multiplication):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
